/** \file
 *  This C header file was generated by $ANTLR version 3.0.1
 *
 *     -  From the grammar source file : Censor.g
 *     -                            On : 2009-12-03 07:19:11
 *     -                 for the lexer : CensorLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 * View this file with tabs set to 8 (:set ts=8 in gvim) and indent at 4 (:set sw=4 in gvim)
 *
 * The lexer CensorLexerhas the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pCensorLexer, which is returned from a call to CensorLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the entry points are provided anyway.
 * * The entry points for CensorLexer are  as follows:
 *
 *  - void      pCensorLexer->T14(pCensorLexer)
 *  - void      pCensorLexer->T15(pCensorLexer)
 *  - void      pCensorLexer->T16(pCensorLexer)
 *  - void      pCensorLexer->COMMENT(pCensorLexer)
 *  - void      pCensorLexer->WHITESPACE(pCensorLexer)
 *  - void      pCensorLexer->SKIP_OP(pCensorLexer)
 *  - void      pCensorLexer->MUTE(pCensorLexer)
 *  - void      pCensorLexer->DIM(pCensorLexer)
 *  - void      pCensorLexer->NON_OP_WORD(pCensorLexer)
 *  - void      pCensorLexer->NUMBER(pCensorLexer)
 *  - void      pCensorLexer->FLOAT(pCensorLexer)
 *  - void      pCensorLexer->DIGIT(pCensorLexer)
 *  - void      pCensorLexer->ROMAN_CHAR(pCensorLexer)
 *  - void      pCensorLexer->Tokens(pCensorLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
#ifndef	_CensorLexer_H
#define _CensorLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef	WIN32
// Disable: Unreferenced parameter,                - Rules with parameters that are not used
//          constant conditional,                  - ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable        - tree rewrite vairables declared but not needed
//          Unreferenced local variable            - lexer rulle decalres but does not always use _type
//          potentially unitialized variable used  - retval always returned from a rule 
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4701 )
#endif



/** Context tracking structure for CensorLexer
 */
typedef struct CensorLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

    void (*mT14)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mT15)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mT16)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mCOMMENT)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mWHITESPACE)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mSKIP_OP)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mMUTE)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mDIM)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mNON_OP_WORD)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mNUMBER)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mFLOAT)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mDIGIT)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mROMAN_CHAR)	(struct CensorLexer_Ctx_struct * ctx);
    void (*mTokens)	(struct CensorLexer_Ctx_struct * ctx);    unsigned char * (*getGrammarFileName)();
    void	    (*free)   (struct CensorLexer_Ctx_struct * ctx);
        
}
    CensorLexer, * pCensorLexer;

/* Function protoypes for the lexer functions that external translation units
 * may wish to call.
 */
ANTLR3_API pCensorLexer CensorLexerNew         (pANTLR3_INPUT_STREAM     instream);/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define SKIP_OP      5
#define MUTE      6
#define NUMBER      8
#define DIM      7
#define WHITESPACE      11
#define FLOAT      9
#define DIGIT      13
#define T14      14
#define T15      15
#define COMMENT      10
#define Tokens      17
#define T16      16
#define ROMAN_CHAR      12
#define EOF      -1
#define NON_OP_WORD      4
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

/* End of token definitions for CensorLexer
 * =============================================================================
 */
/** \} */

#endif
/* END - Note:Keep extra linefeed to satisfy UNIX systems */
